### ISSUE TITLE
How can we do horizontal scroll layout

### ISSUE THREAD

**Issue by bhargavjanispec** [jelenakrmar/circlesLayout#1]
How can we do horizontal scroll layout.

**Comment by jelenakrmar** [comment]
You would change `collectionViewContentSize` and `prepareLayout` methods. 

For `collectionViewContentSize`, the height would be fixed based on the collection view bounds, and width would be dynamically calculated in the `prepareLayout` method.

About `prepareLayout`, I guess X and Y-axis orientation should change. So, for example, you would first increment `originY` until circles reach the bottom of the screen, like this: 

`originX + height + self.viewInsets.right > self.collectionView.bounds.size.width`, where **height** is the same as **width** in the current code since we are talking about circles :) 

and only then, when the bottom is reached, we increment `originX` and continue placing items to the right.

**Comment by bhargavjanispec** [comment]
Hi, @jelenakrmar I have changed the following things, it's scrolling horizontally but not getting proper output, can you please guide me, what I need to do change in this?

first thing i have changed `@property (nonatomic) float contentWidth;` variable name from `contentHeight` in CirclesLayout.h file.

then change following code in CirclesLayout.m file.

```
- (CGSize)collectionViewContentSize {
    return CGSizeMake(self.contentWidth, self.collectionView.bounds.size.height);
}
```

prepareLayout method keep as it is just update variable name `contentWidth` from `contentHeight`

And then I have changed only one line of code in `frameForCircleAtIndexPath` method

` (originX + width + self.viewInsets.right > self.collectionView.bounds.size.height) ` From `(originX + width + self.viewInsets.right > self.collectionView.bounds.size.width)` 


![Simulator Screen Shot - iPhone 8 - 2020-09-26 at 16 41 39](https://user-images.githubusercontent.com/60999353/94339631-f7b54800-0018-11eb-84ea-6f080d8c0590.png)

**Comment by bhargavjanispec** [comment]
Hi, @jelenakrmar  can you please share code snap for this issue? (Horizontal scroll).

**Comment by jelenakrmar** [comment]
Sure, I'll do it later today :)

**Comment by jelenakrmar** [comment]
There were changes in `prepareLayout`, `collectionViewContentSize` and `frameForCircleAtIndexPath:layoutInfo:`.
And also this constant made problems: `kMaxPredecessorNum` (4 was enough for width since phones are narrow).
New code is [pushed to master branch](https://github.com/jelenakrmar/circlesLayout/commit/052f96c1031a3149f43af319895f9803afdebfcd). To switch between horizontal and vertical layout, just edit this line of code: `self.vertical = NO;`

**Comment by bhargavjanispec** [comment]
Wow..Fantastic, Thanks @jelenakrmar,  it's working fine.
